### ISSUE TITLE
Hook Pin

### ISSUE THREAD

**Issue by suportgc** [whmcsred/pin#2]
Olá, bom dia.

é possivel coloca-lo no campo como da imagem abaixo ?
http://prntscr.com/f114kr
Fica mais bonito assim 

seria possivel criar um novo código por dia ?
Gostaria que os pins fossem gerados diariamente, para manter a segurança

**Comment by whmcsred** [comment]
Olá, sim é possível, tudo depende da imaginação e edição.
infelizmente no momento ainda não é possivel, estamos trabalhando em uma nova atualização com muitas novas funções.
